### PR TITLE
Tests enhancement

### PR DESCRIPTION
**Pull request by aezouhri**
<!Pull Request Template>

## Description

<!Please provide a summary of the changes you have made. Include any relevant motivation and context. Mention any dependencies that are required for this change.>
No relevant changes to the UI/UX or the features. Mainly enhancing our test coverage due to feedback on last retrospective presentation.

## Tests
image

## Issues
- #189 
<!Mention any issues or bugs this PR addresses or fixes. Link any related issues.>

## Additional Notes

_Add any other information about the PR here._

---

### CODE REVIEW

**Comment by aezouhri** [comment]
Once PR is ready to merge, please **Squash then merge** as I have a lot of irrelevant commit due to reverting and such.

**Comment by aezouhri** [comment]
@saanbe16 Can you check what is the issues with the server pipeline testing ? I merge main into my branch and I don't understand why it's not passing here but on main it is.

**Comment by saanbe16** [comment]
> @saanbe16 Can you check what is the issues with the server pipeline testing ? I merge main into my branch and I don't understand why it's not passing here but on main it is.

Yeah im looking into it

**Review by saanbe16 — APPROVED** [review]
Great job!

**Pull request merged**
