### PR TITLE
get requests from query instead of body & Extension countdown

### PR DESCRIPTION
**Pull request by saanbe16**
<!Pull Request Template>

## Description

Changing req.bodies to req.queries in the server. Commented out tests but will fix them shortly. Let me know if this fails.

started time till next task on extension as well

Screenshot 2024-03-03 at 3 23 34 PM

## Issues

- #131 
---

### CODE REVIEW

**Comment by saanbe16** [comment]
Don't merge this need to fix something

**Comment by saanbe16** [comment]
> Don't merge this need to fix something

Okay, good now

**Comment by bdesollar** [comment]
Make sure to also put in description what else was changed besides that

**Review by bdesollar — APPROVED** [review]
Looks good thanks Joslin!

**Pull request merged**
