### PR TITLE
Fill in and Update Frequency of Tasks

### PR DESCRIPTION
**Pull request by aezouhri**
<!Pull Request Template>

## Description
<!Please provide a summary of the changes you have made. Include any relevant motivation and context. Mention any dependencies that are required for this change.>
Users can now fill in how often they want to be prompted with a task to complete. 

## Tests
Testing the data value being sent to the database (millisecond) and the data displayed to user (HH:mm format).
## UI Changes
On signup the pop up window has been updated:
image
image

Preference setting page also reflects the change in /preference :
image

## Issues
#76 #77 
<!Mention any issues or bugs this PR addresses or fixes. Link any related issues.>

## Additional Notes

_Add any other information about the PR here._

---

### CODE REVIEW

**Comment by aezouhri** [comment]
@saanbe16 Server tests are not passing, none of my changes should be affecting that. Can you take a look ?

**Review by saanbe16 — COMMENTED** [review]
@aezouhri this is fine for now, but is very ambigiuous from a user perspective. In the future, we'll probably want to change this to be a dropdown with the otion of selecting "every 10mn", "every 30 mn", "every 1 hour" etc

**Review by saanbe16 — APPROVED** [review]

**Comment by aezouhri** [comment]
> @aezouhri this is fine for now, but is very ambigiuous from a user perspective. In the future, we'll probably want to change this to be a dropdown with the otion of selecting "every 10mn", "every 30 mn", "every 1 hour" etc

We'll have to meet up to decide what are reasonable options. Having it freely like that is nice as well, we can add restrictions or give a range if you're worried users will put in 24hr as a value.

**Comment by saanbe16** [comment]
> > @aezouhri this is fine for now, but is very ambigiuous from a user perspective. In the future, we'll probably want to change this to be a dropdown with the otion of selecting "every 10mn", "every 30 mn", "every 1 hour" etc
> 
> We'll have to meet up to decide what are reasonable options. Having it freely like that is nice as well, we can add restrictions or give a range if you're worried users will put in 24hr as a value.

@aezouhri it's more of an ease of use issue, they can put 24h if they'd like, I just feel there are user friendly ways of doing this, but yeah we can talk later

**Pull request merged**
