### PR TITLE
ENH: Update server tests

### PR DESCRIPTION
**Pull request by saanbe16**
<!Pull Request Template>
## Description
This pull request fixes the server tests that were previously failing due to the req.query change

## Tests
Unit and manual testing

## Issues

- #126

### CODE REVIEW

**Review by bdesollar — CHANGES_REQUESTED** [review]
Make sure all tests are passing before committing @saanbe16. I reran it and they still failed.

**Comment by aezouhri** [comment]
@saanbe16 Looking at your code, it seems like when you're creating the tasks you're missing a parameter so it's not fully creating the task. As for the update task, I think your before all is not running properly on that test. Try to only put in before each what you really need across all tests rather than everything and pull the value you want for each test. Just from my personal experience, specially since you might make changes to that "shared" data between tests.

**Comment by saanbe16** [comment]
@aezouhri @bdesollar tests are passing as of now but want to test this further. I made this into a draft pull request, please ignore it until I set it back to nornal

**Comment by saanbe16** [comment]
I added a --runInBand parameter to the package.json to ensure synchronous testing, this should fix the server errors from now on

**Review by bdesollar — APPROVED** [review]
Looks good thanks Joslin.

**Pull request merged**
