### PR TITLE
Login Page

### PR DESCRIPTION
**Pull request by aezouhri**
<!Pull Request Template>

## Description

<!Please provide a summary of the changes you have made. Include any relevant motivation and context. Mention any dependencies that are required for this change.>
Login page has been set up. A form available for submission to connect to db.

## Tests
The tests of the login page are all passing
## UI Changes
image

## Issues
#8  #35
<!Mention any issues or bugs this PR addresses or fixes. Link any related issues.>

## Additional Notes

_Add any other information about the PR here._

---

### CODE REVIEW

**Review by saanbe16 — CHANGES_REQUESTED** [review]
@aezouhri This looks mostly good, can you link the issues related to this pr? Click edit on the conversation and under "issues" write #<issue number> the related issues to this seem like they should be web login, test web login and landing page

**Comment by saanbe16** [comment]
> @aezouhri This looks mostly good, can you link the issues related to this pr? Click edit on the conversation and under "issues" write # the related issues to this seem like they should be web login, test web login and landing page

We want to always link the issue related to the pr under that pr, if an issue for what you are doing doesn't exist make a new issue and link that on under your pr. Then, whenever a pr is closed, we want to make sure to close the related issues as well

**Comment by saanbe16** [comment]
> need to write back-end test
@aezouhri I also noticed you wrote "need to write back-end test" Not completely sure what you mean by this but i made the tests and functionality for the backend "login" and "registration" code earlier today already

**Comment by saanbe16** [comment]
When you update this pr it should be fine, but for immediate next steps you should work on calling the backend apis to actually add users to the database, I'll link documentation on how to do that in the wiki

**Comment by aezouhri** [comment]
> > need to write back-end test
> > @aezouhri I also noticed you wrote "need to write back-end test" Not completely sure what you mean by this but i made the tests and functionality for the backend "login" and "registration" code earlier today already

Yeah I accepted the PR and forgot to read up the code. Wanted to get the page ready first and have you look at the changes. I'll request the PR to be reviewed again once I completed the 3 issues related to sign in.

**Pull request merged**
